#KEY = VALUE
#Browser values can be chrome, firefox, edge, safari
browser = <ENTER_YOUR_BROWSER_HERE>
#application URL
appURL = <ENTER_YOUR_APP_URL_HERE>
#Explicit wait time in seconds
explicitWait = 10
